name = "playground"
type = "javascript"
account_id = "ddcde54ee68c05bfdfbdbf093299be09"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "yarn build:cloudflare"
upload.format = "service-worker"